"""能力模块允许访问的任务面。

直持任务实例的 8 个能力模块各有声明协议: bid / bid_price / recovery / sell /
reading / welfare / assist / popup 已迁到各自的窄协议 (AuctionBidOps /
AuctionBidPriceOps / AuctionRecoveryOps / AuctionSellOps / AuctionReadingOps /
AuctionWelfareOps / AuctionAssistOps / AuctionPopupOps),
模块只访问协议声明的成员。
声明均不为运行时检查, 而是把「模块能碰什么」写进类型系统: 新增跨模块调用
时必须先在对应协议加一行, 评审时就能被看见, 并受 TestAuctionContracts
反射与 AST 扫描用例守卫。成员按现有实际调用面逐条列出; 下划线开头的成员
是任务侧适配器的统一入口约定(见各能力模块的 docstring)。
"""

from typing import Any, Protocol

from ok import Box

from src.scene.PositionMap import PositionMap
from src.tasks.auction.layout import AuctionBoxes


class AuctionPopupOps(Protocol):
    """popup.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按 dismiss_notice_popup 的实际访问面逐条声明, 是直持任务模块中最
    接近框架面的一个: 弹窗识别只依赖 OCR/点击/睡眠与可选预算, 不读写任何
    拍卖业务状态。出价、出售、结算后、回场兜底各流程共用这一个入口;
    任务侧保留同名 delegate 作为装配点与测试 seam。
    """

    # --- 框架 API ---
    def operate_click(self, *args: Any, **kwargs: Any) -> Any: ...
    def ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def sleep(self, timeout: float) -> Any: ...

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _optional_timeout(self, deadline: float | None, limit: float) -> float | None: ...


class AuctionBidPriceOps(Protocol):
    """bid_price.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按合并了模式注册后的 bid_price.py 实际访问面逐条声明: 出价模式的
    分发、价格实现与估价模式的配置校验都在本模块内完成, 直调同模块函数,
    不经任务转发器 —— 任务侧保留的 _apply_heart_increment 等价格转发方法
    是测试直接调用的入口, 不在本协议内。逐口追踪的上轮出价下界读
    last_bid_price, 出价序号读 current_bid_count。
    """

    # --- 状态与配置 ---
    config: dict
    last_bid_price: int | None
    current_bid_count: int
    _smart_state: Any
    _heart_present: bool
    # 资产路由的运行时出价模式覆盖(非 None 表示本次运行已路由, 估价模式
    # 据此不继承「基础价」下限, 见 bid_price.estimate_bid_price)。
    _asset_routed_mode: str | None

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _remaining_timeout(
        self, deadline: float | None, limit: float, message: str = "单轮拍卖超时"
    ) -> float: ...
    def _read_stable_asset_value(self, *args: Any, **kwargs: Any) -> int | None: ...
    def _config_int(self, *args: Any, **kwargs: Any) -> int: ...
    def _config_decimal(self, *args: Any, **kwargs: Any) -> Any: ...
    def _config_int_list(self, *args: Any, **kwargs: Any) -> list[int]: ...
    def _bid_mode(self) -> str: ...
    def _raise_mode(self) -> str: ...


class AuctionRecoveryOps(Protocol):
    """recovery.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按 recovery.py 的实际访问面逐条声明, 比宽协议少掉价格/出售/读数等
    无关面; 编排私有方法(如 _stage_match)不进协议 —— 匹配阶段续跑经
    recover_from_world 的 resume_match 参数由任务侧转发器注入, 模块不回读
    任务编排。回场配额 _recover_quota 的检查与扣减同样留在任务编排层,
    本模块不读写任务状态。任务会经本模块转手给 auction_welfare /
    auction_interaction 的公开函数, 转手后的访问面由对方模块自己的契约
    约束, 不在本协议内。
    """

    # --- 状态与配置 ---
    pos: PositionMap

    # --- 框架 API ---
    def operate_click(self, *args: Any, **kwargs: Any) -> Any: ...
    def ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def wait_ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def box_of_screen(self, *args: Any, **kwargs: Any) -> Box: ...
    def sleep(self, timeout: float) -> Any: ...
    def ensure_main(self, *args: Any, **kwargs: Any) -> Any: ...
    def retry_on_action(self, *args: Any, **kwargs: Any) -> Any: ...
    def openF5panel(self, *args: Any, **kwargs: Any) -> Any: ...
    def in_team_and_world(self) -> bool: ...
    def find_monthly_card(self, *args: Any, **kwargs: Any) -> Any: ...
    def handle_monthly_card(self) -> None: ...
    def info_set(self, key: str, value: object) -> None: ...

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...
    def log_debug(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _optional_timeout(self, deadline: float | None, limit: float) -> float | None: ...
    def _wait_operate_click(self, *args: Any, **kwargs: Any) -> bool: ...
    def _dismiss_notice_popup(self, *args: Any, **kwargs: Any) -> bool: ...
    def _log_aux_error(self, where: str, e: Exception) -> None: ...
    def _return_to_auction(self, boxes: AuctionBoxes, deadline: float) -> bool: ...
    def _read_current_venue(self) -> str: ...
    def _click_instant_lot(self, deadline: float) -> bool: ...
    def _check_expected_venue(
        self, boxes: AuctionBoxes, venue: str | None = None
    ) -> None: ...


class AuctionSellOps(Protocol):
    """sell.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按 sell.py 的实际访问面逐条声明, 比宽协议少掉价格/读数/回场等
    无关面; 品质勾选经 auction_interaction.atomic_sequence 转手 task,
    转手后的访问面由对方模块自己的契约约束, 不在本协议内。跨轮满仓标记
    不由本模块直接改写: run_round_end_sell 以三态返回值报告结论, 由任务侧
    落账 _inventory_stuck。
    """

    # --- 状态与配置 ---
    config: dict
    current_round: int

    # --- 框架 API ---
    def operate_click(self, *args: Any, **kwargs: Any) -> Any: ...
    def ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def wait_ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def box_of_screen(self, *args: Any, **kwargs: Any) -> Box: ...
    def next_frame(self) -> Any: ...

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...
    def log_debug(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _remaining_timeout(
        self, deadline: float | None, limit: float, message: str = "单轮拍卖超时"
    ) -> float: ...
    def _optional_timeout(self, deadline: float | None, limit: float) -> float | None: ...
    def _bounded_sleep(self, deadline: float | None, delay: float) -> None: ...
    def _wait_operate_click(self, *args: Any, **kwargs: Any) -> bool: ...
    def _dismiss_notice_popup(self, *args: Any, **kwargs: Any) -> bool: ...
    def _config_int(self, *args: Any, **kwargs: Any) -> int: ...
    def _sell_qualities(self) -> list[str]: ...
    def _read_asset_value(self, *args: Any, **kwargs: Any) -> int | None: ...
    def _log_aux_error(self, where: str, e: Exception) -> None: ...


class AuctionReadingOps(Protocol):
    """reading.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按 reading.py 的实际访问面逐条声明; POLL_INTERVAL 的所有者仍是
    任务类(匹配/出价/结算共用的轮询节奏)。稳定读取经 _read_estimate_value
    取数, 这是测试的实例级 mock 锚点, 因此保留在协议内。
    """

    # --- 状态与配置 ---
    width: int
    POLL_INTERVAL: float

    # --- 框架 API ---
    def ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def wait_ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def sleep(self, timeout: float) -> Any: ...
    def next_frame(self) -> Any: ...

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...
    def log_debug(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _ocr_upscaled(self, box: Box) -> list: ...
    def _read_estimate_value(
        self, *args: Any, **kwargs: Any
    ) -> tuple[int | None, bool]: ...


class AuctionWelfareOps(Protocol):
    """welfare.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按 welfare.py 的实际访问面逐条声明; 当日领取记录不在任务面上 ——
    WelfareState 状态对象由任务实例持有, 更新只经本模块函数完成。
    """

    # --- 框架 API ---
    def ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def next_frame(self) -> Any: ...

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...
    def log_debug(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _optional_timeout(self, deadline: float | None, limit: float) -> float | None: ...
    def _bounded_sleep(self, deadline: float | None, delay: float) -> None: ...
    def _wait_click_optional(self, *args: Any, **kwargs: Any) -> bool: ...
    def _read_asset_value(self, *args: Any, **kwargs: Any) -> int | None: ...
    def _log_aux_error(self, where: str, e: Exception) -> None: ...


class AuctionBidOps(Protocol):
    """bid.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按 attempt_bid 的实际访问面逐条声明: 单次出价尝试需要的资产读取、
    价格计算、放弃/仪器等辅助入口与屏幕判定都留在任务侧, 它们同时
    是测试的实例级 mock 锚点。出价序号与上轮出价的落账不在协议内 ——
    键盘确认价经任务侧 _input_fixed_price 落账, 出价循环维护 current_bid_count。
    """

    # --- 框架 API ---
    def wait_ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def wait_until(self, *args: Any, **kwargs: Any) -> Any: ...

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...
    def log_debug(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _read_asset_value(self, *args: Any, **kwargs: Any) -> int | None: ...
    def _read_input_range_cap(self, *args: Any, **kwargs: Any) -> int | None: ...
    def _calculate_auction_price(
        self, boxes: AuctionBoxes | None = None, deadline: float | None = None
    ) -> int: ...
    def _remaining_timeout(
        self, deadline: float | None, limit: float, message: str = "单轮拍卖超时"
    ) -> float: ...
    def _abandon_current_auction(self, boxes: AuctionBoxes, deadline: float) -> bool: ...
    def _check_heart_once(self, boxes: AuctionBoxes) -> None: ...
    def _should_abandon_without_heart(self) -> bool: ...
    def _bid_panel_open(self, boxes: AuctionBoxes) -> bool: ...
    def _wait_operate_click(self, *args: Any, **kwargs: Any) -> bool: ...
    def _use_instrument_once(self, boxes: AuctionBoxes, deadline: float) -> None: ...
    def _input_fixed_price(
        self, boxes: AuctionBoxes, price: int | None = None, deadline: float | None = None
    ) -> None: ...
    def _is_bid_screen(self, boxes: AuctionBoxes) -> bool: ...


class AuctionAssistOps(Protocol):
    """assist.py 允许访问的任务面 (仅注解, 无运行时检查)。

    成员按 assist.py 的实际访问面逐条声明; 辅助状态
    (_heart_checked / _heart_present 按场复位, _instrument_served_bid 是按口
    消费的已服务出价序号) 由任务实例持有并随轮重置, 不在本协议内。仪器组装备经
    auction_interaction.scroll_screen 转手 task, 转手后的访问面由对方模块
    自己的契约约束。
    """

    # --- 框架 API ---
    def operate_click(self, *args: Any, **kwargs: Any) -> Any: ...
    def ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def wait_ocr(self, *args: Any, **kwargs: Any) -> list: ...
    def run_and_check_changed(self, *args: Any, **kwargs: Any) -> Any: ...

    # --- 日志 ---
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...
    def log_debug(self, message: str) -> None: ...

    # --- 任务侧适配器入口 ---
    def _optional_timeout(self, deadline: float | None, limit: float) -> float | None: ...
